# Generated by Django 4.2.2 on 2023-06-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_attendees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
