# Generated by Django 4.2.2 on 2023-06-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_attendees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
