# Generated by Django 4.2.2 on 2023-06-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_hashtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.hashtags')),
            ],
        ),
    ]
