# Generated by Django 4.2.2 on 2023-07-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'approved'), ('3', 'suspended'), ('4', 'completed')], max_length=225),
        ),
    ]
