# Generated by Django 4.2.2 on 2023-07-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_hashtags_status_alter_hashtags_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'approved'), ('3', 'suspended'), ('4', 'completed')], default='1', max_length=225),
        ),
    ]
