# Generated by Django 4.2.2 on 2023-07-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_hashtags',
            name='status',
            field=models.CharField(choices=[('1', 'active'), ('2', 'inactive')], default='2', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='status',
            field=models.CharField(choices=[('1', 'active'), ('2', 'inactive')], default='2', max_length=225),
        ),
        migrations.AlterField(
            model_name='follower',
            name='status',
            field=models.CharField(choices=[('1', 'active'), ('2', 'inactive')], default='2', max_length=255),
        ),
        migrations.AlterField(
            model_name='hashtags',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'approved'), ('3', 'suspended')], default='1', max_length=225),
        ),
    ]
