# Generated by Django 4.2.2 on 2023-07-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_eventreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('1', 'Like'), ('2', 'Love'), ('3', 'Wow'), ('4', 'Haha'), ('5', 'Sad'), ('6', 'Angry')], max_length=10),
        ),
    ]
